import ThemeRegistry from "@/theme/ThemeRegistry";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/layout/header";
import HeaderMobile from "@/components/layout/header-mobile";
import Sidebar from "@/components/layout/sidebar";
import MainPage from "@/components/layout/main-page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body className={inter.className}>
          <div className="flex">
            <Sidebar />
            <main className="flex-1">
              <div className="flex flex-col md:ml-60 sm:border-r sm:border-zinc-700 min-h-screen">
                <Header />
                <HeaderMobile />

                <MainPage>{children}</MainPage>
              </div>
            </main>
          </div>
        </body>
      </ThemeRegistry>
    </html>
  );
}
